### PR TITLE
feat: highlighting genes

### PR DESCRIPTION
**Pull request by kvikshaug**

### CODE REVIEW

**Review by BenjaSanchez — APPROVED** [review]
On the user side this works well! @annasirunian might be able to give a proper evaluation of the code :)

**Review by annasirunian — COMMENTED** [review]
Nice! Just need to rename function also here:
https://github.com/DD-DeCaF/escher/blob/master/src/SearchBar.jsx#L153
Not sure what is the desired behavior, but I noticed that in case of no flux, genes are highlighted but reaction is not.

**Comment by BenjaSanchez** [comment]
@annasirunian the reason could be one of the following 3:

* The reaction in the model does not map to the reaction in the map, but the gene does (this gives a hint to the model developer to update the proper map).
* The reaction flux is below 1e-7, in which case it's not displayed due to [this](https://github.com/DD-DeCaF/caffeine-vue/blob/6c9789c1cd6a97d4bb8bf9ee2fba8c7abfb5fae2/src/views/InteractiveMap/Escher.vue#L358) criteria (here I think we should actually address the flux display in a separate issue, by e.g. still showing the flux value in the `data` component of the reaction card even if it was filtered out of the visualization).
* The gene is connected to an isozyme with a high usage in another reaction, as even if the original reaction carries no flux, for the user it's important to know that the gene is still being "used" by some other reaction (this might give clues on how to solve a bottleneck).

If you catch a case that does not fit with any of these 3 scenarios do tell :)

**Comment by kvikshaug** [comment]
> Nice! Just need to rename function also here:
> https://github.com/DD-DeCaF/escher/blob/master/src/SearchBar.jsx#L153

Good catch, thanks :sweat_smile:

**Review by annasirunian — APPROVED** [review]

**Pull request merged**
